services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python run_ingest.py
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
